version: '3'

services:

  frontend:
    build:
      context: /Users/yassineelmaakoul/WebstormProjects/frontend_socle
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: oracleinanutshell/oracle-xe-11g
    volumes :
      - db-vol:/opt/oracle/oradata
    ports:
      - "1521:1521"
    healthcheck:
      test: exit 0
volumes:
  db-vol:
    driver: local